### ISSUE TITLE
openssh does not build with macos 10.15.4

### ISSUE THREAD

**Issue by xdxu** [boltomli/MyMacScripts#2]
Just upgraded to the latest macos 10.15.4, as well as Xcode / Command line tools. Homebrew complains the following when trying to build openssh with ssh1 support:

```
$ brew install boltomli/mymacscripts/openssh --with-ssh1
Updating Homebrew...
==> Installing openssh from boltomli/mymacscripts
==> Installing dependencies for boltomli/mymacscripts/openssh: openssl
==> Installing boltomli/mymacscripts/openssh dependency: openssl
==> Downloading https://homebrew.bintray.com/bottles/openssl@1.1-1.1.1f.catalina.bottle.tar.gz
Already downloaded: /Users/<user>/Library/Caches/Homebrew/downloads/1bb38d99d1db276305363893f5bb6a8256a91987ce4fad6398358b7839f1b0bb--openssl@1.1-1.1.1f.catalina.bottle.tar.gz
==> Pouring openssl@1.1-1.1.1f.catalina.bottle.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@1.1/certs

and run
  /usr/local/opt/openssl@1.1/bin/c_rehash

openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
because openssl/libressl is provided by macOS so don't link an incompatible version.

If you need to have openssl@1.1 first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.bash_profile

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

For pkg-config to find openssl@1.1 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"

==> Summary
🍺  /usr/local/Cellar/openssl@1.1/1.1.1f: 8,057 files, 18MB
==> Installing boltomli/mymacscripts/openssh --with-ssh1
==> Downloading https://www.mirrorservice.org/pub/OpenBSD/OpenSSH/portable/openssh-7.5p1.tar.gz
Already downloaded: /Users/<user>/Library/Caches/Homebrew/downloads/3d884490f9902a172b4775bd3079e321ad73ec747e83b4496540faaae9bddc8d--openssh-7.5p1.tar.gz
==> Downloading https://raw.githubusercontent.com/Homebrew/patches/1860b0a74/openssh/patch-sandbox-darwin.c-apple-sandbox-named-e
Already downloaded: /Users/<user>/Library/Caches/Homebrew/downloads/a17e2d1a6f18e7a70cbdcc17330dfa2cb554f9bd8573347299c3b66f5a41b3fe--patch-sandbox-darwin.c-apple-sandbox-named-external.diff
==> Downloading https://raw.githubusercontent.com/Homebrew/patches/d8b2d8c2/openssh/patch-sshd.c-apple-sandbox-named-external.dif
Already downloaded: /Users/<user>/Library/Caches/Homebrew/downloads/bbbc8e6e998ba302dda52e8a77fe78e28659349a36700774b564db5a16aa2a42--patch-sshd.c-apple-sandbox-named-external.diff
==> Patching
==> Applying patch-sandbox-darwin.c-apple-sandbox-named-external.diff
patching file sandbox-darwin.c
Hunk #1 succeeded at 63 (offset 1 line).
==> Applying patch-sshd.c-apple-sandbox-named-external.diff
patching file sshd.c
Hunk #1 succeeded at 619 (offset -94 lines).
==> ./configure --with-libedit --with-kerberos5 --prefix=/usr/local/Cellar/openssh/7.5p1 --sysconfdir=/usr/local/etc/ssh --with-p
==> make
Last 15 lines from /Users/<user>/Library/Logs/Homebrew/openssh/02.make:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libopenbsd-compat.a(strlcat.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libopenbsd-compat.a(strlcpy.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libopenbsd-compat.a(strmode.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libopenbsd-compat.a(strnlen.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libopenbsd-compat.a(strptime.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libopenbsd-compat.a(strsep.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libopenbsd-compat.a(strtoll.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libopenbsd-compat.a(strtoul.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libopenbsd-compat.a(strtoull.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libopenbsd-compat.a(timingsafe_bcmp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libopenbsd-compat.a(port-aix.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libopenbsd-compat.a(port-irix.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libopenbsd-compat.a(port-linux.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libopenbsd-compat.a(port-solaris.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libopenbsd-compat.a(port-uw.o) has no symbols

If reporting this issue please do so to (not Homebrew/brew or Homebrew/core):
  boltomli/mymacscripts

Traceback (most recent call last):
	23: from /usr/local/Homebrew/Library/Homebrew/build.rb:196:in `<main>'
	22: from /usr/local/Homebrew/Library/Homebrew/build.rb:114:in `install'
	21: from /usr/local/Homebrew/Library/Homebrew/utils.rb:478:in `with_env'
	20: from /usr/local/Homebrew/Library/Homebrew/build.rb:117:in `block in install'
	19: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1128:in `brew'
	18: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2077:in `stage'
	17: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
	16: from /usr/local/Homebrew/Library/Homebrew/resource.rb:75:in `stage'
	15: from /usr/local/Homebrew/Library/Homebrew/resource.rb:95:in `unpack'
	14: from /usr/local/Homebrew/Library/Homebrew/resource.rb:171:in `mktemp'
	13: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
	12: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
	11: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
	10: from /usr/local/Homebrew/Library/Homebrew/resource.rb:172:in `block in mktemp'
	 9: from /usr/local/Homebrew/Library/Homebrew/resource.rb:100:in `block in unpack'
	 8: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2101:in `block in stage'
	 7: from /usr/local/Homebrew/Library/Homebrew/utils.rb:478:in `with_env'
	 6: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2102:in `block (2 levels) in stage'
	 5: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1133:in `block in brew'
	 4: from /usr/local/Homebrew/Library/Homebrew/build.rb:146:in `block (2 levels) in install'
	 3: from /usr/local/Homebrew/Library/Taps/boltomli/homebrew-mymacscripts/Formula/openssh.rb:54:in `install'
	 2: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1905:in `system'
	 1: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1905:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1968:in `block in system': Failed executing: make (BuildError)
	9: from /usr/local/Homebrew/Library/Homebrew/brew.rb:38:in `<main>'
	8: from /usr/local/Homebrew/Library/Homebrew/brew.rb:143:in `rescue in <main>'
	7: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:413:in `dump'
	6: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:359:in `issues'
	5: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:363:in `fetch_issues'
	4: from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:305:in `issues_for_formula'
	3: from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:291:in `search_issues'
	2: from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:400:in `search'
	1: from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:225:in `open_api'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:271:in `raise_api_error': Validation Failed: [{"message"=>"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.", "resource"=>"Search", "field"=>"q", "code"=>"invalid"}] (GitHub::ValidationFailedError)
```

brew configurations are as follows:
```
$ brew --config
HOMEBREW_VERSION: 2.2.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: fa8fe0fc396550c23156043cd07550fc6ae6a27a
Last commit: 12 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d5b88cb32af096274f57a672a3d7410791c9faf3
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 12.0.2, 12
macOS: 10.15.4-x86_64
CLT: 11.4.0.0.1.1583798712
Xcode: 11.4
```
Please let me know if you need any additional information.

**Comment by boltomli** [comment]
Thanks for the nice report, clean and complete. I, however, don't know how to make the obsolete version to be compatible with latest macOS. Consider this is not secure, perhaps you'll need some other solution if it's really needed.

**Comment by xdxu** [comment]
The only need for me is to ssh to mitbbs.com with Welly. Anyway it is not a big deal :)
